# docker-compose.override.yml
# Override file for development environment
# This file is automatically loaded by docker-compose

version: '3.8'

services:
  jack-bridge:
    environment:
      - LOG_LEVEL=DEBUG
      - JACK_BRIDGE_VERBOSE=true
    volumes:
      - ./jack-bridge/src:/app/src:ro
      - ./jack-bridge/include:/app/include:ro
      - ./jack-bridge/config:/app/config
    ports:
      - '6666:6666'
      - '6667:6667'
      - '9999:9999' # Debug port

  jack-router:
    profiles: [] # Override profile to make it available by default
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=DEBUG
      - HOT_RELOAD_ENABLED=true
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    ports:
      - '3001:3001'
      - '3443:3443'
      - '5173:5173'
      - '9229:9229' # Node.js debug port
    command: npm run dev

  mosquitto:
    volumes:
      - ./mosquitto/dev-config:/mosquitto/config:ro
    environment:
      - MOSQUITTO_LOG_TYPE=all

  redis:
    command: redis-server --loglevel verbose

  # Additional development services
  pgadmin:
    profiles: ['dev', 'admin']
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - jack-network

  portainer:
    profiles: ['dev', 'admin']
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - jack-network

volumes:
  pgadmin-data:
  portainer-data:
