# docker-compose.yml - Development-focused setup
version: '3.8'

services:
  # MQTT Broker (Docker service)
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: jack-audio-mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '7777:7777'
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - jack-network
    extra_hosts:
      - "jack-bridge:172.18.16.1"
      - "host.docker.internal:172.18.16.1"
    healthcheck:
      test:
        [
          'CMD',
          'mosquitto_pub',
          '-h',
          'localhost',
          '-t',
          'test',
          '-m',
          'test',
          '--quiet',
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # JACK Audio Router - DEVELOPMENT MODE (default)
  jack-router:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: jack-audio-router-dev
    restart: unless-stopped
    ports:
      - '5555:5555' # HTTP port
      - '5556:5556' # HTTPS port
      - '5173:5173' # Vite dev server
      - '9229:9229' # Node.js debug port
    volumes:
      # Mount entire project for hot reload
      - .:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
      # Mount additional directories for development
      - ./logs:/app/logs
      - router-ssl:/app/ssl
      - router-state:/app/state
    environment:
      # Development environment
      - NODE_ENV=development
      - PORT=5555
      - HTTPS_PORT=5556
      - HOST=0.0.0.0
      - DEPLOYMENT_MODE=hybrid-dev

      # JACK Bridge connection (LOCAL Windows service)
      - JACK_BRIDGE_HOST=172.18.16.1
      - JACK_BRIDGE_PORT=6666
      - JACK_BRIDGE_WS_PORT=6667

      # MQTT configuration
      - MQTT_ENABLED=true
      - MQTT_HOST=mqtt://mosquitto:1883
      - MQTT_CLIENT_ID=jack-audio-router-dev

      # SSL Configuration (auto-generate for dev)
      - SSL_ENABLED=true
      - SSL_AUTO_GENERATE=true
      - FORCE_HTTPS=false

      # Development-specific settings
      - LOG_LEVEL=DEBUG
      - LOG_COLORS=true
      - HOT_RELOAD_ENABLED=true
      - DEV_PROXY_TARGET=http://localhost:5173

      # Features
      - FEATURE_SSL_ENABLED=true
      - FEATURE_MQTT_ENABLED=true
      - FEATURE_STATE_PERSISTENCE=true
      - FEATURE_CONNECTION_TRACKING=true
      - FEATURE_HEALTH_MONITORING=true

      # State management
      - STATE_AUTO_SAVE_INTERVAL=10000
      - STATE_BACKUP_ENABLED=true

    depends_on:
      mosquitto:
        condition: service_healthy
    networks:
      - jack-network
    extra_hosts:
      - "jack-bridge:172.18.16.1"
      - "host.docker.internal:172.18.16.1"
    # Development doesn't need health checks (faster startup)
    command: ['npm', 'run', 'dev']

  # JACK Audio Router - PRODUCTION MODE (opt-in)
  jack-router-prod:
    profiles: ['production']
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: jack-audio-router-prod
    restart: unless-stopped
    ports:
      - '5555:5555'
      - '5556:5556'
    volumes:
      - router-state:/app/state
      - router-ssl:/app/ssl
      - router-logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=5555
      - HTTPS_PORT=5556
      - HOST=0.0.0.0
      - DEPLOYMENT_MODE=hybrid

      - JACK_BRIDGE_HOST=172.18.16.1
      - JACK_BRIDGE_PORT=6666
      - JACK_BRIDGE_WS_PORT=6667

      - MQTT_ENABLED=true
      - MQTT_HOST=mqtt://mosquitto:1883
      - MQTT_CLIENT_ID=jack-audio-router-prod

      - SSL_ENABLED=true
      - SSL_AUTO_GENERATE=true
      - FORCE_HTTPS=true

      - LOG_LEVEL=INFO
      - LOG_COLORS=false
      - LOG_FILE_ENABLED=true
      - LOG_FILE_PATH=/app/logs/jack-router.log

      - FEATURE_SSL_ENABLED=true
      - FEATURE_MQTT_ENABLED=true
      - FEATURE_STATE_PERSISTENCE=true
      - FEATURE_CONNECTION_TRACKING=true
      - FEATURE_HEALTH_MONITORING=true

      - STATE_AUTO_SAVE_INTERVAL=30000
      - STATE_BACKUP_ENABLED=true

    depends_on:
      mosquitto:
        condition: service_healthy
    networks:
      - jack-network
    extra_hosts:
      - "jack-bridge:172.18.16.1"
      - "host.docker.internal:172.18.16.1"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5555/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis (Optional - for caching and session management)
  redis:
    profiles: ['cache']
    image: redis:7-alpine
    container_name: jack-audio-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - jack-network
    extra_hosts:
      - "jack-bridge:172.18.16.1"
      - "host.docker.internal:172.18.16.1"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  jack-network:
    driver: bridge
    name: jack-audio-network

volumes:
  # Router service volumes
  router-state:
    driver: local
    name: jack-router-state
  router-ssl:
    driver: local
    name: jack-router-ssl
  router-logs:
    driver: local
    name: jack-router-logs

  # MQTT service volumes
  mosquitto-data:
    driver: local
    name: jack-mosquitto-data
  mosquitto-logs:
    driver: local
    name: jack-mosquitto-logs

  # Redis volumes (optional)
  redis-data:
    driver: local
    name: jack-redis-data

